AppTerceraPreEntregaEscobarMatias/urls.py
from django.urls import path, include
from AppTerceraPreEntregaEscobarMatias import views

app_name= "AppTerceraPreEntregaEscobarMatias"

urlpatterns = [
    path('AppTerceraPreEntregaEscobarMatias', views.inicio, name="inicio"),
    path ("cliente/", views.cliente, name="cliente"),
    path("vendedor/", views.vendedor, name= "vendedor"),
    path("proveedor/", views.proveedor, name= "proveedor"),
    path("patrocinante/", views.patrocinante, name= "patrocinante"),
    #path("clienteFormulario", views.clienteFormulario, name="clienteFormulario"),
    #path("vendedorFormulario", views.vendedorFormulario, name="vendedorFormulario"),
    #path("proveedorFormulario", views.proveedorFormulario, name="proveedorFormulario"),
    #path("patrocinanteFormulario", views.patrocinanteFormulario, name="patrocinanteFormulario"),
    path("busquedaCliente", views.busquedaCliente, name="busquedaCliente"),
    path("buscar/", views.buscar),
    path ("leerCliente/", views.leerCliente, name="leerCliente"),
    path ("leerVendedor/", views.leerVendedor, name="leerVendedor"),
    path ("leerProveedor/", views.leerProveedor, name="LeerProveedor"),
    path ("leerPatrocinante/", views.leerPatrocinante, name="LeerleerPatrocinante"),
    path ("eliminarCliente/<cliente_nombre>/", views.eliminarCliente, name="eliminarCliente"),
    path ("editarCliente/<cliente_nombre>/", views.editarCliente, name= "editarCliente"),
    
    ]

TerceraPreEntregaEscobarMatias/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("AppTerceraPreEntregaEscobarMatias/", include ("AppTerceraPreEntregaEscobarMatias.urls")),
]

AppTerceraPreEntregaEscobarMatias/models.py
from django.db import models

# Create your models here.

class Cliente (models.Model):
 
    nombre=models.CharField(max_length=40)
    apellido=models.CharField(max_length=40)
    dni=models.IntegerField()
    email=models.EmailField()
    profesion=models.CharField(max_length=30)

    def __str__(self):
        return f"nombre:{self.nombre} - apellido:{self.apellido} - dni:{self.dni} - email: {self.email} - profesion: {self.profesion}"

class Vendedor(models.Model):
    nombre=models.CharField(max_length=40)
    apellido=models.CharField(max_length=40)
    dni=models.IntegerField()
    email=models.EmailField()

    def __str__(self):
        return f"nombre:{self.nombre} - apellido:{self.apellido} - dni:{self.dni} - email: {self.email}"

class Proveedor(models.Model):
    nombre=models.CharField(max_length=40)
    apellido=models.CharField(max_length=40)
    dni=models.IntegerField()
    email=models.EmailField()
    marca=models.CharField(max_length=30)

    def __str__(self):
        return f"nombre:{self.nombre} - apellido:{self.apellido} - dni:{self.dni} - email: {self.email} - marca: {self.marca}"

class Patrocinante(models.Model):
    nombre=models.CharField(max_length=40)
    apellido=models.CharField(max_length=40)
    dni=models.IntegerField()
    email=models.EmailField()
    marca=models.CharField(max_length=30)


    def __str__(self):
        return f"nombre:{self.nombre} - apellido:{self.apellido} - dni:{self.dni} - email: {self.email} - marca: {self.marca}"

AppTerceraPreEntregaEscobarMatias/forms.py
from django import forms


class ClienteFormulario(forms.Form):
    nombre=forms.CharField(max_length=40)
    apellido=forms.CharField(max_length=40)
    dni=forms.IntegerField()
    email=forms.EmailField()
    profesion=forms.CharField(max_length=30)

class VendedorFormulario(forms.Form):
    nombre=forms.CharField(max_length=40)
    apellido=forms.CharField(max_length=40)
    dni=forms.IntegerField()
    email=forms.EmailField()

class ProveedorFormulario(forms.Form):
    nombre=forms.CharField(max_length=40)
    apellido=forms.CharField(max_length=40)
    dni=forms.IntegerField()
    email=forms.EmailField()
    marca=forms.CharField(max_length=30)

class PatrocinanteFormulario(forms.Form):
    nombre=forms.CharField(max_length=40)
    apellido=forms.CharField(max_length=40)
    dni=forms.IntegerField()
    email=forms.EmailField()
    marca=forms.CharField(max_length=30)

AppTerceraPreEntregaEscobarMatias/views.py
from django.shortcuts import render
from django.http import HttpResponse
from AppTerceraPreEntregaEscobarMatias.models import Cliente, Vendedor, Proveedor, Patrocinante
from AppTerceraPreEntregaEscobarMatias.forms import ClienteFormulario, VendedorFormulario, ProveedorFormulario, PatrocinanteFormulario

# Create your views here.
"""
def cliente(self):
    cliente= Cliente (nombre="Matias", apellido="Escobar" dni=12123123, email="matias@coder.it")
    cliente.save()

    documentoDeTexto= f"--- nombre:{cliente.nombre} apellido: {cliente.apellido} dni: {cliente.dni} email: {cliente.email}"
    return HttpResponse (documentoDeTexto)
"""

def inicio (request):
    return render (request, "inicio.html")


def cliente(request):
    if request.method =="POST":
        miFormulario= ClienteFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:

            informacion=miFormulario.cleaned_data

        cliente= Cliente (nombre=informacion ["nombre"],
                          apellido=informacion ["apellido"],
                          dni=informacion ["dni"],
                          email=informacion ["email"],
                          profesion=informacion ["profesion"],)
            
        cliente.save()

        return render(request, "inicio.html")
    else:
        miFormulario= ClienteFormulario()

    return render(request, "cliente.html", {"miFormulario":miFormulario})


def vendedor(request):
    if request.method =="POST":
        miFormulario= VendedorFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:

            informacion=miFormulario.cleaned_data

        vendedor= Vendedor (nombre=informacion ["nombre"],
                          apellido=informacion ["apellido"],
                          dni=informacion ["dni"],
                          email=informacion ["email"],)
            
        vendedor.save()

        return render(request, "inicio.html")
    else:
        miFormulario= VendedorFormulario()

    return render(request, "vendedor.html", {"miFormulario":miFormulario})

def proveedor(request):
    if request.method =="POST":
        miFormulario= ProveedorFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:

            informacion=miFormulario.cleaned_data

        proveedor= Proveedor (nombre=informacion ["nombre"],
                          apellido=informacion ["apellido"],
                          dni=informacion ["dni"],
                          email=informacion ["email"],
                          marca=informacion ["marca"],)
            
        proveedor.save()

        return render(request, "inicio.html")
    else:
        miFormulario= ProveedorFormulario()

    return render(request, "proveedor.html", {"miFormulario":miFormulario})

def patrocinante(request):
    if request.method =="POST":
        miFormulario= PatrocinanteFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:

            informacion=miFormulario.cleaned_data

        patrocinante= Patrocinante(nombre=informacion ["nombre"],
                          apellido=informacion ["apellido"],
                          dni=informacion ["dni"],
                          email=informacion ["email"],
                          marca=informacion ["marca"],)
            
        patrocinante.save()

        return render(request, "inicio.html")
    else:
        miFormulario= PatrocinanteFormulario()

    return render(request, "patrocinante.html", {"miFormulario":miFormulario})


def busquedaCliente (request):
    return render (request, "busquedaCliente.html")

def buscar (request):
   if request.GET["dni"]:
       dni= request.GET["dni"]
       cliente= Cliente.objects.filter(dni__icontains=dni)

       return render(request, "resultadoBusqueda.html", {"cliente":cliente, "dni":dni})
   
   else:
       respuesta= "No enviaste datos."
   
   return HttpResponse(respuesta)

def leerCliente(request):
    cliente= Cliente.objects.all()
    contexto = {"cliente": cliente}
    return render (request, "leerCliente.html", contexto)

def leerVendedor(request):
    vendedor= Vendedor.objects.all()
    contexto = {"vendedor": vendedor}
    return render (request, "leerVendedor.html", contexto)

def leerProveedor(request):
    proveedor= Proveedor.objects.all()
    contexto = {"proveedor": proveedor}
    return render (request, "leerProveedor.html", contexto)

def leerPatrocinante(request):
    patrocinante= Patrocinante.objects.all()
    contexto = {"patrocinante": patrocinante}
    return render (request, "leerPatrocinante.html", contexto)

def eliminarCliente(request, cliente_nombre):
    cliente= Cliente.objects.get(nombre=cliente_nombre)
    cliente.delete()

    cliente=Cliente.objects.all()
    contexto = {"cliente": cliente}
    return render (request, "leerCliente.html", contexto)

def editarCliente(request, cliente_nombre):
    cliente= Cliente.objects.get(nombre=cliente_nombre)

    if request.method == "POST":
        miFormulario= ClienteFormulario(request.POST)

        print(miFormulario)

        if miFormulario.is_valid(): 
            informacion= miFormulario.cleaned_data

            cliente.nombre= informacion ["nombre"]
            cliente.apellido= informacion ["apellido"]
            cliente.dni= informacion ["dni"]
            cliente.email= informacion ["email"]
            cliente.profesion= informacion ["profesion"]

            cliente.save()

            return render(request, "inicio.html")
        
    else:
        miFormulario= ClienteFormulario(initial={"nombre": cliente.nombre, 
                                                     "apellido":cliente.apellido, 
                                                     "dni":cliente.dni, 
                                                     "email":cliente.email, 
                                                     "profesion": cliente.profesion})
            
        return render (request, "editarCliente.html",
                            {"miFormulario":miFormulario, "cliente_nombre":cliente_nombre})

AppTerceraPreEntregaEscobarMatias/templates/busquedaCliente.html
{% extends "padre.html" %}
{% load static %}

{% block contenidoQueCambia %}

    <h1>Cliente </h1>
    
    
        <form action="/AppTerceraPreEntregaEscobarMatias/buscar/" method="GET">
       
            <input type="number" name="dni" id="dni" placeholder="Ingrese su DNI...">
    
            <input type="submit" value="Buscar">
    
        </form>

    
 

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/cliente.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <h1>Cliente </h1>
    
    {% if miFormulario.errors %}
    <p style="color: red;"> Están mal los datos, revisar.</p>

    {% endif %}

    <form action="" method="POST"> {% csrf_token %}
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">

    </form>
 

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/editarCliente.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <h1>Cliente </h1>
    
    {% if miFormulario.errors %}
    <p style="color: red;"> Están mal los datos, revisar.</p>

    {% endif %}

    <form action="cliente" method="POST"> {% csrf_token %}
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">

    </form>
 

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/eliminarCliente1.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


<body>
    
    {% for p in cliente %}
        <li> {{p}} </li>
        <button>
            <a href "{% url "AppTerceraPreEntregaEscobarMatias:eliminarCliente" p.nombre %}">Eliminar</a>
        </button>
    {% endfor %}
    <br>
    
</body>

            <a class="btn btn-primary" href="{% url "cliente"%}">AGREGAR CLIENTE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                
            </div>
        </div>
    </nav>

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/inicio.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <h1>Bienvenidos a la revolución del sistema. </h1>
    <p>Estas preparado para adentrarte en este maravilloso mundo? </p>



{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/leerCliente.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


<body>
    
    {% for p in cliente %}
    <li> {{p}} </li>


        <a class="btn btn-primary" href="{% url "AppTerceraPreEntregaEscobarMatias:eliminarCliente" p.nombre %}">ELIMINAR CLIENTE</a>
        <a class="btn btn-primary" href="{% url "AppTerceraPreEntregaEscobarMatias:editarCliente" p.nombre %}">EDITAR CLIENTE</a>
    
    {% endfor %}
<br>

</body>

            <a class="btn btn-primary" href="{% url "AppTerceraPreEntregaEscobarMatias:cliente"%}">AGREGAR CLIENTE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                
            </div>
        </div>
    </nav>

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/leerProveedor.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


<body>
    
    {% for p in proveedor %}
        <li> {{p}} </li>
    {% endfor %}
</body>

            <a class="btn btn-primary" href="{% url "proveedor"%}">AGREGAR PROVEEDOR</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                
            </div>
        </div>
    </nav>

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/leerVendedor.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


<body>
    
    {% for p in vendedor %}
    <li> {{p}} </li>
    <button>
        <a href "{% url "eliminarVendedor" p.nombre %}">Eliminar</a>
    </button>
    {% endfor %}
<br>

</body>

            <a class="btn btn-primary" href="{% url "vendedor"%}">AGREGAR VENDEDOR</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                
            </div>
        </div>
    </nav>

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/leerpatrocinante.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


<body>
    
    {% for p in patrocinante %}
        <li> {{p}} </li>
    {% endfor %}
</body>

            <a class="btn btn-primary" href="{% url "patrocinante"%}">AGREGAR PATROCINANTE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                
            </div>
        </div>
    </nav>

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>One Page Wonder - MATECH </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= "{% static "AppTerceraPreEntregaEscobarMatias/css/styles.css"%}" rel="stylesheet" />
    
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                
                <a class="navbar-brand" href="{% url "AppTerceraPreEntregaEscobarMatias:inicio"%}">Inicio</a>
                <a class="navbar-brand" href="{% url "AppTerceraPreEntregaEscobarMatias:cliente"%}">Cliente</a>
                <a class="navbar-brand" href="{% url "AppTerceraPreEntregaEscobarMatias:vendedor"%}">Vendedor</a>
                <a class="navbar-brand" href="{% url "AppTerceraPreEntregaEscobarMatias:proveedor"%}">Proveedor</a>
                <a class="navbar-brand" href="{% url "AppTerceraPreEntregaEscobarMatias:patrocinante"%}">Patrocinante</a>
                <a class="btn btn-primary" href="{% url "AppTerceraPreEntregaEscobarMatias:busquedaCliente"%}">BUSCAR CLIENTE</a>
                <a class="btn btn-primary" href="{% url "AppTerceraPreEntregaEscobarMatias:leerCliente"%}">LEER CLIENTE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">M A T E C H</h1>
                    <h2 class="masthead-subheading mb-0">Soluciones Informáticas</h2>
                    
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>

        {% block contenidoQueCambia%}

        {% endblock %}
      
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        
                        <div class="footerSocials">
                            <a href="https://www.facebook.com/">INSTAGRAM</a>
                            <a href="https://www.instagram.com/">FACEBOOK</a>        
                               
                          </div>
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; MeE 2023. All Rights Reserved.</p>
                    </div>
                    
                </div>
            </div>
        </footer>


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

AppTerceraPreEntregaEscobarMatias/templates/patrocinante.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <h1>Patrocinante </h1>
    
    {% if miFormulario.errors %}
    <p style="color: red;"> Están mal los datos, revisar.</p>

    {% endif %}

    <form action="" method="POST"> {% csrf_token %}
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">

    </form>
 

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/proveedor.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <h1>Proveedor </h1>
    
    {% if miFormulario.errors %}
    <p style="color: red;"> Están mal los datos, revisar.</p>

    {% endif %}

    <form action="" method="POST"> {% csrf_token %}
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">

    </form>
 

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/resultadoBusqueda.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


 



<body>
    <p>El cliente con el D.N.I. Nro.  {{dni}} es: </p>

    {% if cliente %}

    <ul>
    {% for cliente in cliente %}
        <li> {{cliente.nombre}} </li>
        <li> {{cliente.apellido}} </li>
        <li> {{cliente.dni}} </li>
        <li> {{cliente.email}} </li>
        <li> {{cliente.profesion}} </li>
    {% endfor %}
    </ul>

    {% endif %}
</body>
</html>

{% endblock %}

AppTerceraPreEntregaEscobarMatias/templates/vendedor.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <h1>Vendedor </h1>
    
    {% if miFormulario.errors %}
    <p style="color: red;"> Están mal los datos, revisar.</p>

    {% endif %}

    <form action="" method="POST"> {% csrf_token %}
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">

    </form>
 

{% endblock %}